### ISSUE TITLE
Independent viewer component for embedding

### ISSUE THREAD

**Issue by Hydragyrum** [honzaap/Systemizer#15]
Would it be possible to separate the viewer component such that it can take a JSON file and display it as an embedded format à la mermaidJS? This will make it easier to embed a read-only version for documentation purposes.

**Comment by honzaap** [comment]
This could be possible, there is a [similar Issue](https://github.com/honzaap/Systemizer/issues/7) that will export the board as png except what you're saying would be perphaps SVG. I mean something like [drawio](https://app.diagrams.net/) File->Embed->SVG function.

**Comment by Hydragyrum** [comment]
I was thinking more exporting the json and rendering it on the fly

**Comment by honzaap** [comment]
There are certainly a lot of pros this would bring, however I don't think that it would be possible now. It would mean a lot of changes and I'm not sure I even know where to start. I will try to look into more way to export the system outside the app after creating the "export as png/svg" and maybe even try this method. It will take some time though...

**Comment by Hydragyrum** [comment]
No problem, it'll probably mean decoupling the board view from the rest of the app somehow

**Comment by honzaap** [comment]
Most of the UI was decoupled, only things that are essential for the board are present in the component. The `<app-board>` can now take in a JSON object, like: `<app-board [loadedSave]="saveObject"></app-board>`. If this object is provided, it will be loaded instead of the last modified save. You can also pass in `[isReadOnly]="true"`, which will render the board without component and options menu, and will provide a bottom menu for controls. This is the method used for IFrame embedding that was made in the honzaap/Systemizer@c417412 commit. Even though it's not exactly like the example of mermaidJS I believe that this Issue can be closed with this. Any future embedding options will be also done with this method. If you have any issues, feel free to ask, create a new Issue or reopen this one.
